// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };

import Navbar from "~/components/navbar";

  
  export default function Layout({ children }: { children: React.ReactNode }) {
    return (
      <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow p-4">{children}</main>
        <footer className="bg-gray-800 text-white p-4">Footer Content</footer>
      </div>
    );
  }