// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };

import Footer from "~/components/home/footer";
import Navbar from "~/components/navbar";

  
  export default function Layout({ children }: { children: React.ReactNode }) {
    return (
      <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow p-4">{children}</main>
        <Footer />
      </div>
    );
  }